services:
  go-app:
    build: .
    container_name: go-app-container
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - .:/app
      - ./snapshots:/data
    environment:
      - SNAPSHOT_PATH=/data
      - PORT=8080